version: '3'

services:
   mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: Test
      MYSQL_USER: iizuka
      MYSQL_PASSWORD: iizuka
      MYSQL_ROOT_PASSWORD: iizuka
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    volumes:
      # データボリュームのマウント
      - mysql:/var/lib/mysql
      # DDLや初期データ投入
      - ./mysql/sql:/docker-entrypoint-initdb.d
      # MySQLの設定ファイル
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  mysql:
